### ISSUE TITLE
nanomsg build process have some errors

### ISSUE THREAD

**Issue by mezzovide** [SuperNETorg/SuperNET#7]
make[1]: Entering directory `/root/btcd/libjl777/nanomsg'
  CC       src/core/libnanomsg_la-ep.lo
  CC       src/core/libnanomsg_la-epbase.lo
  CC       src/core/libnanomsg_la-global.lo
**src/core/global.c: In function 'nn_global_submit_counter':
src/core/global.c:1007:9: warning: implicit declaration of function 'gmtime_r' [-Wimplicit-function-declaration]
         gmtime_r (&numtime, &strtime);
         ^
src/core/global.c: In function 'nn_global_submit_errors':
src/core/global.c:1110:23: warning: implicit declaration of function '_snprintf_s' [-Wimplicit-function-declaration]
                 len = _snprintf_s (curbuf, buf_left, _TRUNCATE,
                       ^**
  CC       src/core/libnanomsg_la-pipe.lo
  CC       src/core/libnanomsg_la-poll.lo
  CC       src/core/libnanomsg_la-sock.lo
  CC       src/core/libnanomsg_la-sockbase.lo
  CC       src/core/libnanomsg_la-symbol.lo
  CC       src/aio/libnanomsg_la-ctx.lo
  CC       src/aio/libnanomsg_la-fsm.lo
  CC       src/aio/libnanomsg_la-poller.lo
  CC       src/aio/libnanomsg_la-pool.lo
  CC       src/aio/libnanomsg_la-timer.lo
  CC       src/aio/libnanomsg_la-timerset.lo
  CC       src/aio/libnanomsg_la-usock.lo
  CC       src/aio/libnanomsg_la-worker.lo
**In file included from src/aio/../utils/err.h:33:0,
                 from src/aio/worker_win.inc:27,
                 from src/aio/worker.c:26:
src/aio/worker_win.inc: In function 'nn_worker_routine':
src/aio/../utils/fast.h:27:38: warning: passing argument 1 of '__builtin_expect' makes integer from pointer without a cast [-Wint-conversion]
 #define nn_fast(x) __builtin_expect ((x), 1)
                                      ^
src/aio/worker_win.inc:176:17: note: in expansion of macro 'nn_fast'
             if (nn_fast (entries [i].lpOverlapped)) {
                 ^
src/aio/../utils/fast.h:27:38: note: expected 'long int' but argument is of type 'LPOVERLAPPED {aka struct _OVERLAPPED *}'
 #define nn_fast(x) __builtin_expect ((x), 1)
                                      ^
src/aio/worker_win.inc:176:17: note: in expansion of macro 'nn_fast'
             if (nn_fast (entries [i].lpOverlapped)) {
                 ^**
  CC       src/utils/libnanomsg_la-alloc.lo
  CC       src/utils/libnanomsg_la-atomic.lo
  CC       src/utils/libnanomsg_la-chunk.lo
  CC       src/utils/libnanomsg_la-chunkref.lo
  CC       src/utils/libnanomsg_la-clock.lo
  CC       src/utils/libnanomsg_la-closefd.lo
  CC       src/utils/libnanomsg_la-efd.lo
  CC       src/utils/libnanomsg_la-err.lo
  CC       src/utils/libnanomsg_la-glock.lo
  CC       src/utils/libnanomsg_la-hash.lo
  CC       src/utils/libnanomsg_la-list.lo
  CC       src/utils/libnanomsg_la-msg.lo
  CC       src/utils/libnanomsg_la-mutex.lo
  CC       src/utils/libnanomsg_la-queue.lo
  CC       src/utils/libnanomsg_la-random.lo
  CC       src/utils/libnanomsg_la-sem.lo
  CC       src/utils/libnanomsg_la-sleep.lo
  CC       src/utils/libnanomsg_la-stopwatch.lo
  CC       src/utils/libnanomsg_la-thread.lo
  CC       src/utils/libnanomsg_la-wire.lo
  CC       src/protocols/bus/libnanomsg_la-bus.lo
  CC       src/protocols/bus/libnanomsg_la-xbus.lo
  CC       src/protocols/pipeline/libnanomsg_la-push.lo
  CC       src/protocols/pipeline/libnanomsg_la-pull.lo
  CC       src/protocols/pipeline/libnanomsg_la-xpull.lo
  CC       src/protocols/pipeline/libnanomsg_la-xpush.lo
  CC       src/protocols/pair/libnanomsg_la-pair.lo
  CC       src/protocols/pair/libnanomsg_la-xpair.lo
  CC       src/protocols/pubsub/libnanomsg_la-pub.lo
  CC       src/protocols/pubsub/libnanomsg_la-sub.lo
  CC       src/protocols/pubsub/libnanomsg_la-trie.lo
  CC       src/protocols/pubsub/libnanomsg_la-xpub.lo
  CC       src/protocols/pubsub/libnanomsg_la-xsub.lo
  CC       src/protocols/reqrep/libnanomsg_la-req.lo
  CC       src/protocols/reqrep/libnanomsg_la-rep.lo
  CC       src/protocols/reqrep/libnanomsg_la-task.lo
  CC       src/protocols/reqrep/libnanomsg_la-xrep.lo
  CC       src/protocols/reqrep/libnanomsg_la-xreq.lo
  CC       src/protocols/survey/libnanomsg_la-respondent.lo
  CC       src/protocols/survey/libnanomsg_la-surveyor.lo
  CC       src/protocols/survey/libnanomsg_la-xrespondent.lo
  CC       src/protocols/survey/libnanomsg_la-xsurveyor.lo
  CC       src/protocols/utils/libnanomsg_la-dist.lo
  CC       src/protocols/utils/libnanomsg_la-excl.lo
  CC       src/protocols/utils/libnanomsg_la-fq.lo
  CC       src/protocols/utils/libnanomsg_la-lb.lo
  CC       src/protocols/utils/libnanomsg_la-priolist.lo
  CC       src/transports/utils/libnanomsg_la-backoff.lo
  CC       src/transports/utils/libnanomsg_la-dns.lo
  CC       src/transports/utils/libnanomsg_la-iface.lo
  CC       src/transports/utils/libnanomsg_la-literal.lo
  CC       src/transports/utils/libnanomsg_la-port.lo
  CC       src/transports/utils/libnanomsg_la-streamhdr.lo
  CC       src/transports/utils/libnanomsg_la-base64.lo
  CC       src/transports/inproc/libnanomsg_la-binproc.lo
  CC       src/transports/inproc/libnanomsg_la-cinproc.lo
  CC       src/transports/inproc/libnanomsg_la-inproc.lo
  CC       src/transports/inproc/libnanomsg_la-ins.lo
  CC       src/transports/inproc/libnanomsg_la-msgqueue.lo
  CC       src/transports/inproc/libnanomsg_la-sinproc.lo
  CC       src/transports/ipc/libnanomsg_la-aipc.lo
  CC       src/transports/ipc/libnanomsg_la-bipc.lo
  CC       src/transports/ipc/libnanomsg_la-cipc.lo
  CC       src/transports/ipc/libnanomsg_la-ipc.lo
  CC       src/transports/ipc/libnanomsg_la-sipc.lo
  CC       src/transports/tcp/libnanomsg_la-atcp.lo
  CC       src/transports/tcp/libnanomsg_la-btcp.lo
  CC       src/transports/tcp/libnanomsg_la-ctcp.lo
  CC       src/transports/tcp/libnanomsg_la-stcp.lo
  CC       src/transports/tcp/libnanomsg_la-tcp.lo
  CC       src/transports/ws/libnanomsg_la-aws.lo
  CC       src/transports/ws/libnanomsg_la-bws.lo
  CC       src/transports/ws/libnanomsg_la-cws.lo
  CC       src/transports/ws/libnanomsg_la-sws.lo
  CC       src/transports/ws/libnanomsg_la-ws.lo
  CC       src/transports/ws/libnanomsg_la-ws_handshake.lo
  CC       src/transports/ws/libnanomsg_la-sha1.lo
  CC       src/transports/tcpmux/libnanomsg_la-atcpmux.lo
  CC       src/transports/tcpmux/libnanomsg_la-btcpmux.lo
  CC       src/transports/tcpmux/libnanomsg_la-ctcpmux.lo
  CC       src/transports/tcpmux/libnanomsg_la-stcpmux.lo
  CC       src/transports/tcpmux/libnanomsg_la-tcpmux.lo
  CC       src/devices/libnanomsg_la-device.lo
  CC       src/devices/libnanomsg_la-tcpmuxd.lo
  CCLD     libnanomsg.la

*** Warning: linker path does not have real file for library -lMswsock.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because I did check the linker path looking for a file starting
*** with libMswsock and none of the candidates passed a file format test
*** using a file magic. Last file checked: /root/btcd/libjl777/mxe/usr/i686-w64-mingw32.static/lib/libws2_32.a
*** The inter-library dependencies that have been dropped here will be
*** automatically added whenever a program is linked with this library
*** or is declared to -dlopen it.

*** Since this library must not contain undefined symbols,
*** because either the platform does not support them or
*** it was explicitly requested with -no-undefined,
*** libtool will only create a static version of it.
  CC       tools/nanocat.o
  CC       tools/options.o
tools/options.c: In function 'nn_process_option':
tools/options.c:455:24: warning: implicit declaration of function '_snprintf_s' [-Wimplicit-function-declaration]
             data_len = _snprintf_s (data, data_buf, _TRUNCATE, opt->pointer,
                        ^
  CCLD     nanocat.exe
/root/btcd/libjl777/mxe/usr/bin/i686-w64-mingw32.static-ld: cannot find -lMswsock
collect2: error: ld returned 1 exit status
make[1]: *** [nanocat.exe] Error 1
make[1]: Leaving directory `/root/btcd/libjl777/nanomsg'

**Comment by satindergrewal** [comment]
nanomesg gave warnings but compiled fine with latest updates by jl777
